services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  order-service:
    build:
      context: ./app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres:5432/payments

  fake-gateway:
    build:
      context: ./gateway
    ports:
      - "8001:8001"

volumes:
  postgres_data: